---
- name: Install Packages
  yum:
    name:
      - httpd
      - php
      - php-mysql
    state: present

- name: Give writable mode to http folder
  file:
   path: /var/www/html
   state: directory
   mode: 0755
   
- name: permit traffic in default zone for https service
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: restart and enable systemd apache service
  systemd:
    name: httpd
    enabled: yes
    state: enabled
