---
- name: install mariadb package
  yum:
   name: 
    - mariadb
    - mariadb-server
   state: present

- name: restart and enable systemd mariadb service
  systemd:
    name: mariadb
    state: started
    enabled: yes
   

- name: Start mysql_secure_installation
  command: 'echo "& y y Monmotdepasse Monmotdepasse y y y y" | ./usr/bin/mysql_secure_installation'

- name: restart and enable systemd mariadb service
  systemd:
    name: mariadb
    enabled: yes
    state: restarted
